stages:
  - publish

default:
  tags:
    - executor-docker
    - public
  image:
    name: node:lts
    pull_policy: if-not-present
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
    
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-10 --activate
    - pnpm config set store-dir .pnpm-store
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - echo "git-checks=false" >> ~/.npmrc
    - pnpm install --frozen-lockfile

variables:
  PACKAGE:
    value: "shared"
    description: "The package to publish"
    options:
      - "shared"
      - "uniapp"
      - "vue3-hooks"
      - "vue3-element-plus"
  
publish_shared:
  stage: publish
  script:
    - pnpm run build:shared
    - git status
    - pnpm run publish:shared
  rules:
    - if: $CI_SERVER_HOST !~ /^gitlab\.hykj\..*/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /bump[shared]/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /shared/
    - if: $CI_PIPELINE_SOURCE == "web" && $PACKAGE == "shared"

publish_uniapp:
  stage: publish
  script:
    - pnpm run build:uniapp
    - git status
    - pnpm run publish:uniapp
  rules:
    - if: $CI_SERVER_HOST !~ /^gitlab\.hykj\..*/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /bump[uniapp]/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /uniapp/
    - if: $CI_PIPELINE_SOURCE == "web" && $PACKAGE == "uniapp"

publish_vue3_hooks:
  stage: publish
  script:
    - pnpm run build:vue3-hooks
    - git status
    - pnpm run publish:vue3-hooks
  rules:
    - if: $CI_SERVER_HOST !~ /^gitlab\.hykj\..*/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /bump[vue3-hooks]/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /vue3-hooks/
    - if: $CI_PIPELINE_SOURCE == "web" && $PACKAGE == "vue3-hooks"

publish_vue3_element_plus:
  stage: publish
  script:
    - pnpm run build:vue3-element-plus
    - git status
    - pnpm run publish:vue3-element-plus
  rules:
    - if: $CI_SERVER_HOST !~ /^gitlab\.hykj\..*/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /bump[vue3-element-plus]/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /vue3-element-plus/
    - if: $CI_PIPELINE_SOURCE == "web" && $PACKAGE == "vue3-element-plus"
