/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConcatList: typeof import('./components/concatList.vue')['default']
    DictInputTest: typeof import('./components/dictInput-test.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTag: typeof import('element-plus/es')['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAndReloadBtn: typeof import('./components/searchAndReloadBtn.vue')['default']
    UploadAnyTest: typeof import('./components/uploadAny-test.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const ConcatList: typeof import('./components/concatList.vue')['default']
  const DictInputTest: typeof import('./components/dictInput-test.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchAndReloadBtn: typeof import('./components/searchAndReloadBtn.vue')['default']
  const UploadAnyTest: typeof import('./components/uploadAny-test.vue')['default']
}